import { Menu } from './type';

export const mockMenu: Menu = {
  _innerMap: {},
  actionCode: 'menu',
  actionType: 'menu',
  allowModify: 1,
  apiDelIds: [],
  apiList: [],
  applicationCategoryId: '1',
  applicationId: '1',
  departmentId: '1',
  description: '菜单',
  displayDepartment: '1',
  displayRecordUser: '1',
  formId: '1',
  frontendActionCode: 'menu',
  frontendApiUrl: '',
  frontendPageId: '',
  frontendPathName: '',
  fullPath: '',
  funcDelIds: [],
  functionList: [
    {
      _innerMap: undefined,
      actionId: '',
      applicationId: '',
      departmentId: '',
      description: '',
      displayDepartment: '',
      displayRecordUser: '',
      frontendActionFunctionCode: '',
      frontendApiUrl: 'k5kc5wp92ur',
      frontendFunctionCode: '',
      frontendPageId: '',
      frontendPathName: '',
      functionCategory: '',
      functionCode: '',
      icon: '',
      iconCss: '',
      id: 'k5kc5wp92ur',
      modifyTime: '',
      name: 'fffff',
      orderIndex: 0,
      recordTime: '',
      recordUser: '',
      refActionFunctionId: '',
      shortName: 'f',
      systemId: '',
      tempStorage: 0,
      templateId: '',
      url: 'k5kc5wp92ur',
      uuid: '',
    },
    {
      _innerMap: undefined,
      actionId: '',
      applicationId: '',
      departmentId: '',
      description: '',
      displayDepartment: '',
      displayRecordUser: '',
      frontendActionFunctionCode: '',
      frontendApiUrl: '',
      frontendFunctionCode: '',
      frontendPageId: '',
      frontendPathName: '',
      functionCategory: '',
      functionCode: '',
      icon: '',
      iconCss: '',
      id: '"yrfrnyzmwlf"',
      modifyTime: '',
      name: '分组一',
      orderIndex: 0,
      recordTime: '',
      recordUser: '',
      refActionFunctionId: '',
      shortName: '一',
      systemId: '',
      tempStorage: 0,
      functionList: [
        {
          _innerMap: undefined,
          actionId: '',
          applicationId: '',
          departmentId: '',
          description: '',
          displayDepartment: '',
          displayRecordUser: '',
          frontendActionFunctionCode: '',
          frontendApiUrl: 'nocobase-admin-menu_111',
          frontendFunctionCode: '',
          frontendPageId: '',
          frontendPathName: '',
          functionCategory: '',
          functionCode: '',
          icon: '',
          iconCss: '',
          id: 'nocobase-admin-menu_111',
          modifyTime: '',
          name: 'test111',
          orderIndex: 0,
          recordTime: '',
          recordUser: '',
          refActionFunctionId: '',
          shortName: 't',
          systemId: '',
          tempStorage: 0,
          templateId: '',
          url: 'nocobase-admin-menu_111',
          uuid: '',
        },
      ],
      templateId: '',
      url: '',
      uuid: '',
    },
  ],
  hasChildren: 0,
  icon: '',
  id: '',
  isBlock: false,
  isBuiltin: 0,
  isDataDelete: 0,
  isDataEditing: 0,
  isDialog: 0,
  isExpanded: 0,
  isFollow: false,
  isFrontendSyncAction: false,
  isHide: 0,
  isLeaf: 0,
  isLink: 0,
  key: '',
  level: 0,
  linkType: '',
  linkUrl: '',
  modifyTime: '',
  name: '',
  orderIndex: 0,
  originalNamePath: '',
  parentId: '',
  parentKey: '',
  pathname: '',
  recordTime: '',
  recordUser: '',
  refActionId: '',
  resourceType: '',
  shortName: '',
  systemId: '',
  tempStorage: 0,
  templateId: '',
  topRankingNumber: 0,
  treeLevel: 0,
  uuid: '',
};

export function transformUsmMenu(menu: Menu) {
  return menu.functionList.map((item: any) => {
    const { name, frontendApiUrl } = item;
    return {
      ...item,
      label: name,
      key: frontendApiUrl,
      children: item?.functionList?.length ? transformUsmMenu(item) : undefined,
    };
  });
}
